// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Movies.Filter
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    internal enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "score")]
        #pragma warning disable CS1591
        Score,
        #pragma warning restore CS1591
        [EnumMember(Value = "firstAired")]
        #pragma warning disable CS1591
        FirstAired,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
    }
}
