// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Updates
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    internal enum GetActionQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
    }
}
