// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Updates
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    internal enum GetTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "artwork")]
        #pragma warning disable CS1591
        Artwork,
        #pragma warning restore CS1591
        [EnumMember(Value = "award_nominees")]
        #pragma warning disable CS1591
        Award_nominees,
        #pragma warning restore CS1591
        [EnumMember(Value = "companies")]
        #pragma warning disable CS1591
        Companies,
        #pragma warning restore CS1591
        [EnumMember(Value = "episodes")]
        #pragma warning disable CS1591
        Episodes,
        #pragma warning restore CS1591
        [EnumMember(Value = "lists")]
        #pragma warning disable CS1591
        Lists,
        #pragma warning restore CS1591
        [EnumMember(Value = "people")]
        #pragma warning disable CS1591
        People,
        #pragma warning restore CS1591
        [EnumMember(Value = "seasons")]
        #pragma warning disable CS1591
        Seasons,
        #pragma warning restore CS1591
        [EnumMember(Value = "series")]
        #pragma warning disable CS1591
        Series,
        #pragma warning restore CS1591
        [EnumMember(Value = "seriespeople")]
        #pragma warning disable CS1591
        Seriespeople,
        #pragma warning restore CS1591
        [EnumMember(Value = "artworktypes")]
        #pragma warning disable CS1591
        Artworktypes,
        #pragma warning restore CS1591
        [EnumMember(Value = "award_categories")]
        #pragma warning disable CS1591
        Award_categories,
        #pragma warning restore CS1591
        [EnumMember(Value = "awards")]
        #pragma warning disable CS1591
        Awards,
        #pragma warning restore CS1591
        [EnumMember(Value = "company_types")]
        #pragma warning disable CS1591
        Company_types,
        #pragma warning restore CS1591
        [EnumMember(Value = "content_ratings")]
        #pragma warning disable CS1591
        Content_ratings,
        #pragma warning restore CS1591
        [EnumMember(Value = "countries")]
        #pragma warning disable CS1591
        Countries,
        #pragma warning restore CS1591
        [EnumMember(Value = "entity_types")]
        #pragma warning disable CS1591
        Entity_types,
        #pragma warning restore CS1591
        [EnumMember(Value = "genres")]
        #pragma warning disable CS1591
        Genres,
        #pragma warning restore CS1591
        [EnumMember(Value = "languages")]
        #pragma warning disable CS1591
        Languages,
        #pragma warning restore CS1591
        [EnumMember(Value = "movies")]
        #pragma warning disable CS1591
        Movies,
        #pragma warning restore CS1591
        [EnumMember(Value = "movie_genres")]
        #pragma warning disable CS1591
        Movie_genres,
        #pragma warning restore CS1591
        [EnumMember(Value = "movie_status")]
        #pragma warning disable CS1591
        Movie_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "peopletypes")]
        #pragma warning disable CS1591
        Peopletypes,
        #pragma warning restore CS1591
        [EnumMember(Value = "seasontypes")]
        #pragma warning disable CS1591
        Seasontypes,
        #pragma warning restore CS1591
        [EnumMember(Value = "sourcetypes")]
        #pragma warning disable CS1591
        Sourcetypes,
        #pragma warning restore CS1591
        [EnumMember(Value = "tag_options")]
        #pragma warning disable CS1591
        Tag_options,
        #pragma warning restore CS1591
        [EnumMember(Value = "tags")]
        #pragma warning disable CS1591
        Tags,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedcharacters")]
        #pragma warning disable CS1591
        Translatedcharacters,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedcompanies")]
        #pragma warning disable CS1591
        Translatedcompanies,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedepisodes")]
        #pragma warning disable CS1591
        Translatedepisodes,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedlists")]
        #pragma warning disable CS1591
        Translatedlists,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedmovies")]
        #pragma warning disable CS1591
        Translatedmovies,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedpeople")]
        #pragma warning disable CS1591
        Translatedpeople,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedseasons")]
        #pragma warning disable CS1591
        Translatedseasons,
        #pragma warning restore CS1591
        [EnumMember(Value = "translatedserierk")]
        #pragma warning disable CS1591
        Translatedserierk,
        #pragma warning restore CS1591
    }
}
