// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Artwork;
using ApiSdk.Awards;
using ApiSdk.Characters;
using ApiSdk.Companies;
using ApiSdk.Content;
using ApiSdk.Countries;
using ApiSdk.Entities;
using ApiSdk.Episodes;
using ApiSdk.Genders;
using ApiSdk.Genres;
using ApiSdk.Inspiration;
using ApiSdk.Languages;
using ApiSdk.Lists;
using ApiSdk.Login;
using ApiSdk.Movies;
using ApiSdk.People;
using ApiSdk.Search;
using ApiSdk.Seasons;
using ApiSdk.Series;
using ApiSdk.Sources;
using ApiSdk.Updates;
using ApiSdk.User;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ApiSdk
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class ApiClient : BaseRequestBuilder
    {
        /// <summary>The artwork property</summary>
        public global::ApiSdk.Artwork.ArtworkRequestBuilder Artwork
        {
            get => new global::ApiSdk.Artwork.ArtworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The awards property</summary>
        public global::ApiSdk.Awards.AwardsRequestBuilder Awards
        {
            get => new global::ApiSdk.Awards.AwardsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The characters property</summary>
        public global::ApiSdk.Characters.CharactersRequestBuilder Characters
        {
            get => new global::ApiSdk.Characters.CharactersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The companies property</summary>
        public global::ApiSdk.Companies.CompaniesRequestBuilder Companies
        {
            get => new global::ApiSdk.Companies.CompaniesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The content property</summary>
        public global::ApiSdk.Content.ContentRequestBuilder Content
        {
            get => new global::ApiSdk.Content.ContentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The countries property</summary>
        public global::ApiSdk.Countries.CountriesRequestBuilder Countries
        {
            get => new global::ApiSdk.Countries.CountriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The entities property</summary>
        public global::ApiSdk.Entities.EntitiesRequestBuilder Entities
        {
            get => new global::ApiSdk.Entities.EntitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episodes property</summary>
        public global::ApiSdk.Episodes.EpisodesRequestBuilder Episodes
        {
            get => new global::ApiSdk.Episodes.EpisodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The genders property</summary>
        public global::ApiSdk.Genders.GendersRequestBuilder Genders
        {
            get => new global::ApiSdk.Genders.GendersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The genres property</summary>
        public global::ApiSdk.Genres.GenresRequestBuilder Genres
        {
            get => new global::ApiSdk.Genres.GenresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The inspiration property</summary>
        public global::ApiSdk.Inspiration.InspirationRequestBuilder Inspiration
        {
            get => new global::ApiSdk.Inspiration.InspirationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The languages property</summary>
        public global::ApiSdk.Languages.LanguagesRequestBuilder Languages
        {
            get => new global::ApiSdk.Languages.LanguagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::ApiSdk.Lists.ListsRequestBuilder Lists
        {
            get => new global::ApiSdk.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The login property</summary>
        public global::ApiSdk.Login.LoginRequestBuilder Login
        {
            get => new global::ApiSdk.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The movies property</summary>
        public global::ApiSdk.Movies.MoviesRequestBuilder Movies
        {
            get => new global::ApiSdk.Movies.MoviesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The people property</summary>
        public global::ApiSdk.People.PeopleRequestBuilder People
        {
            get => new global::ApiSdk.People.PeopleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::ApiSdk.Search.SearchRequestBuilder Search
        {
            get => new global::ApiSdk.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seasons property</summary>
        public global::ApiSdk.Seasons.SeasonsRequestBuilder Seasons
        {
            get => new global::ApiSdk.Seasons.SeasonsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The series property</summary>
        public global::ApiSdk.Series.SeriesRequestBuilder Series
        {
            get => new global::ApiSdk.Series.SeriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sources property</summary>
        public global::ApiSdk.Sources.SourcesRequestBuilder Sources
        {
            get => new global::ApiSdk.Sources.SourcesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The updates property</summary>
        public global::ApiSdk.Updates.UpdatesRequestBuilder Updates
        {
            get => new global::ApiSdk.Updates.UpdatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::ApiSdk.User.UserRequestBuilder User
        {
            get => new global::ApiSdk.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.ApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api4.thetvdb.com/v4";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
