// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Series.Filter
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    internal enum GetSortTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "asc")]
        #pragma warning disable CS1591
        Asc,
        #pragma warning restore CS1591
        [EnumMember(Value = "desc")]
        #pragma warning disable CS1591
        Desc,
        #pragma warning restore CS1591
    }
}
