// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Series.Item.Extended
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    internal enum GetMetaQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "translations")]
        #pragma warning disable CS1591
        Translations,
        #pragma warning restore CS1591
        [EnumMember(Value = "episodes")]
        #pragma warning disable CS1591
        Episodes,
        #pragma warning restore CS1591
    }
}
