// <auto-generated/>
#pragma warning disable CS0618
using ApiSdk.Movies.Filter;
using ApiSdk.Movies.Item;
using ApiSdk.Movies.Slug;
using ApiSdk.Movies.Statuses;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Movies
{
    /// <summary>
    /// Builds and executes requests for operations under \movies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    internal partial class MoviesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The filter property</summary>
        public global::ApiSdk.Movies.Filter.FilterRequestBuilder Filter
        {
            get => new global::ApiSdk.Movies.Filter.FilterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The slug property</summary>
        public global::ApiSdk.Movies.Slug.SlugRequestBuilder Slug
        {
            get => new global::ApiSdk.Movies.Slug.SlugRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The statuses property</summary>
        public global::ApiSdk.Movies.Statuses.StatusesRequestBuilder Statuses
        {
            get => new global::ApiSdk.Movies.Statuses.StatusesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the ApiSdk.movies.item collection</summary>
        /// <param name="position">id</param>
        /// <returns>A <see cref="global::ApiSdk.Movies.Item.MoviesItemRequestBuilder"/></returns>
        public global::ApiSdk.Movies.Item.MoviesItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::ApiSdk.Movies.Item.MoviesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Movies.MoviesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoviesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/movies{?page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.Movies.MoviesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MoviesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/movies{?page*}", rawUrl)
        {
        }
        /// <summary>
        /// returns list of movie base records
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Movies.MoviesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.Movies.MoviesGetResponse?> GetAsync(Action<RequestConfiguration<global::ApiSdk.Movies.MoviesRequestBuilder.MoviesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.Movies.MoviesGetResponse> GetAsync(Action<RequestConfiguration<global::ApiSdk.Movies.MoviesRequestBuilder.MoviesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ApiSdk.Movies.MoviesGetResponse>(requestInfo, global::ApiSdk.Movies.MoviesGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// returns list of movie base records
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Movies.MoviesRequestBuilder.MoviesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.Movies.MoviesRequestBuilder.MoviesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.Movies.MoviesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.Movies.MoviesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiSdk.Movies.MoviesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// returns list of movie base records
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        internal partial class MoviesRequestBuilderGetQueryParameters 
        {
            /// <summary>page number</summary>
            [QueryParameter("page")]
            public double? Page { get; set; }
        }
    }
}
#pragma warning restore CS0618
